import { roll } from "../services/Dice/Dice"

export const forenames = [
	'Augost',
	'Augosta',
	'Benedict',
	'Benedicta',
	'Brin',
	'Breen',
	'Chumwan',
	'Chumwel',
	'Calahed',
	'Calit',
	'Dorren',
	'Dorret',
	'Emmett',
	'Emma',
	'Felix',
	'Felora',
	'Fred',
	'Freda',
	'Grobin',
	'Grobina',
	'Gizard',
	'Giza',
	'Helroff',
	'Helriel',
	'Istan',
	'Isti',
	'Ilmer',
	'Ilda',
	'Junas',
	'Julia',
	'Katsun',
	'Katsin',
	'Lurpax',
	'Lunda',
	'Litton',
	'Littona',
	'Munfud',
	'Munfi',
	'Narmun',
	'Nadya',
	'Orren',
	'Orrena',
	'Podder',
	'Poddin',
	'Peta',
	'Picklow',
	'Pickelle',
	'Pipp',
	'Pippita',
	'Quinn',
	'Rosher',
	'Roshel',
	'Stellan',
	'Stella',
	'Samford',
	'Sambay',
	'Tucker',
	'Tuckis',
	'Teevan',
	'Teeva',
	'Urntin',
	'Urna',
	'Varran',
	'Varin',
	'Vanis',
	'Vanissa',
	'Volta',
	'Voltel',
	'Weckster',
	'Weckin',
	'Yurnak',
	'Yurna',
	'Zarm',
]

export const surnames = [
	'Allane',
	'Bargroll',
	'Brunfield',
	'Chop',
	'Creed',
	'Dunbell',
	'Eggler',
	'Fox',
	'Farsee',
	'Gill',
	'Gullwin',
	'Huckle',
	'Horrican',
	'Ingle',
	'Jongler',
	'Kross',
	'Lix',
	'Lowbile',
	'Montane',
	'Nutbush',
	'Olifant',
	'Offenpot',
	'Ouze',
	'Phile',
	'Parfait',
	'Quigley',
	'Regal',
	'Stagger',
	'Shark',
	'Tumble',
	'Terrine',
	'Underhog',
	'Upperill',
	'Volfhole',
	'Vinifera',
	'Wickerspin',
	'Yarn',
	'Zarrack',
]

export const occupations = [
	'Actor',
	'Barge Pilot',
	'Butler',
	'Coffee House Host',
	'Coal Miner',
	'Dog Breeder',
	'Engine Cleaner',
	'Fist Fighter',
	'Fishmonger',
	'Gull-Catcher',
	'Glue maker',
	'Gunsmith',
	'Gin-Maker',
	'Hog-Slaughterer',
	'Ivory Worker',
	'Jeweler',
	'Lower-Politician',
	'Life Servant',
	'Lamp-Lighter',
	'Lesser-Noble',
	'Mercenary',
	'Newspaper Vendor',
	'Octopus-Catcher',
	'Oyster Seller',
	'Perfumer',
	'Professor',
	'Prison Guard',
	'Pie-Smith',
	'Road Sweeper',
	'Salt Farmer',
	'Sweet-Maker',
	'Trinket-Merchant',
	'Tax Collector',
	'Tunnel Digger',
	'Whaler',
	'Watchmaker',
	'Watchman',
	'Writer',
	'Wigmaker',
]

export const capabilities = [
	'Anal-Retentive',
	'Boringly Dependable',
	'Best in the City',
	'Cheap and Dirty',
	'Charming and Oily',
	'Dabbler',
	'Expensive and Flashy',
	'Fair and Down to Earth',
	'Filthy but very cheap',
	'Great, but hated for it',
	'Good but Annoying',
	'Highly Artistic',
	'Hardly trained',
	'Inherited Family Trade',
	'Interested in new career',
	'Imposter',
	'Jealous of Better Rival',
	'Learning, still.',
	'Loves the job',
	'Lazy and Greedy',
	'Money-Grabbing',
	'Moral, but not that good',
	'Only serves friends',
	'Old-Master-Trained',
	'Perfectionist',
	'Paragon of the Job',
	'Poor from bad business',
	'Retired from Injury',
	'Ruthless',
	'Sworn into Profession',
	'Silently dutiful',
	'Trained from Birth',
	'Trapped in Job',
	'Uncaring',
	'Unreliable Genius',
	'Wedded into Career',
	'Wasted Talent',
	'Warm and Friendly',
	'Wealthy with Success',
]

export function characterBackground() {
	return {
		forename: forenames[roll(`d${forenames.length}`) - 1],
		surname: surnames[roll(`d${surnames.length}`) - 1],
		occupation: occupations[roll(`d${occupations.length}`) - 1],
		capability: capabilities[roll(`d${capabilities.length}`) - 1]
	}
}